# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)
development:
  adapter: mysql
  database: asset_tracking-dev
  user: root

test:
  adapter: mysql
  database: asset_tracking-test
  user: root

production:
  adapter: mysql
  database: asset_tracking
  user: root
