development:
  adapter: mysql
  database: assets-dev
  username: root

test:
  adapter: mysql
  database: assets-test
  username: root

production:
  adapter: mysql
  database: assets
  username: root
